# Generated by Django 4.2.7 on 2023-11-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enName', models.CharField(max_length=255)),
                ('shortName', models.CharField(max_length=100)),
                ('educationTypeName', models.CharField(max_length=20)),
                ('financingTypeName', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('militaryRegistered', models.BooleanField()),
                ('diploma', models.CharField(max_length=10)),
                ('hei', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.hei')),
            ],
        ),
    ]
