# Generated by Django 4.2.7 on 2023-11-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrant',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
