# Generated by Django 4.2.7 on 2023-11-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0002_rename_lastname_entrant_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrant',
            name='militaryRegistered',
        ),
        migrations.AddField(
            model_name='entrant',
            name='military_registered',
            field=models.BooleanField(default=False, verbose_name='Перебування на військовому обліку'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='diploma',
            field=models.CharField(max_length=10, verbose_name='Диплом'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='hei',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.hei', verbose_name='Заклад вищої освіти'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='name',
            field=models.CharField(max_length=20, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='patronymic',
            field=models.CharField(max_length=20, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон +380xx1234567'),
        ),
    ]
