# Generated by Django 4.2.7 on 2023-11-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0003_remove_entrant_militaryregistered_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HEI',
            new_name='University',
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['shortName']},
        ),
        migrations.RenameField(
            model_name='entrant',
            old_name='hei',
            new_name='university',
        ),
    ]
