# Generated by Django 4.2.7 on 2023-11-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0004_rename_hei_university_alter_university_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['shortName'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['shortName'],
            },
        ),
        migrations.RemoveField(
            model_name='entrant',
            name='military_registered',
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('сathedra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vstup.cathedra', verbose_name='Кафедра')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Onp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enName', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Обсяг (кредитів)')),
                ('accredited', models.BooleanField(default=False, verbose_name='Акредитовано')),
                ('accredited_by', models.DateField(help_text='Введіть дату акредитації', verbose_name='Дата акредитації')),
                ('id_edebo', models.IntegerField(verbose_name='ID ЄДЕБО')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vstup.specialty', verbose_name='Спеціальність')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vstup.faculty', verbose_name='Факультет'),
        ),
    ]
