# Generated by Django 4.2.7 on 2023-11-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0005_cathedra_faculty_remove_entrant_military_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onp',
            name='accredited',
        ),
        migrations.RemoveField(
            model_name='onp',
            name='accredited_by',
        ),
        migrations.RemoveField(
            model_name='onp',
            name='id_edebo',
        ),
        migrations.RemoveField(
            model_name='onp',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='сathedra',
        ),
        migrations.AddField(
            model_name='entrant',
            name='military_registered',
            field=models.BooleanField(default=False, verbose_name='Перебування на військовому обліку'),
        ),
        migrations.AddField(
            model_name='onp',
            name='cathedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vstup.cathedra', verbose_name='Кафедра'),
        ),
    ]
