# Generated by Django 4.2.7 on 2023-11-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0006_remove_onp_accredited_remove_onp_accredited_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onp',
            name='cathedra',
        ),
        migrations.AddField(
            model_name='cathedra',
            name='specialty',
            field=models.ManyToManyField(help_text='Спеціальність', to='vstup.specialty'),
        ),
        migrations.AddField(
            model_name='onp',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vstup.specialty', verbose_name='Спеціальність'),
        ),
    ]
