# Generated by Django 4.2.7 on 2023-11-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0008_remove_onp_specialty_specialty_onp'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='birth_date',
            field=models.DateField(default='1980-01-01', verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='diploma_avg',
            field=models.IntegerField(default=0, help_text='Середній бал диплому про вищу освіту (зазначений у додатку до диплому)', verbose_name='Середній бал диплому'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='diploma_date',
            field=models.DateField(default='1980-01-01', verbose_name='Дата видачі диплому'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='diploma_with_honors',
            field=models.BooleanField(default=False, verbose_name='Диплом з відзнакою'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='gender',
            field=models.CharField(choices=[('Ч', 'Чоловік'), ('Ж', 'Жінка')], max_length=1, null=True, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='level',
            field=models.IntegerField(choices=[(1, 'Магістр (науковий рівень)'), (2, 'Магістр (професійний рівень)'), (3, 'Спеціаліст')], default=3),
        ),
        migrations.AddField(
            model_name='entrant',
            name='tck',
            field=models.CharField(max_length=100, null=True, verbose_name='Повна назва РТЦК та СП (РВК)'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='diploma',
            field=models.CharField(max_length=10, verbose_name='Серія, № диплому'),
        ),
    ]
