# Generated by Django 4.2.7 on 2023-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0009_entrant_birth_date_entrant_diploma_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='tck',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Повна назва РТЦК та СП (РВК)'),
        ),
    ]
