# Generated by Django 4.2.7 on 2023-11-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0011_entrant_cathedra_entrant_specialty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='cathedra',
            old_name='specialty',
            new_name='specialties',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='number',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='onp',
        ),
        migrations.CreateModel(
            name='CathedraSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vstup.cathedra')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vstup.specialty')),
            ],
        ),
    ]
