# Generated by Django 4.2.7 on 2023-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0012_alter_specialty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='cathedras',
            field=models.ManyToManyField(help_text='Кафедра', to='vstup.cathedra'),
        ),
    ]
