# Generated by Django 4.2.7 on 2023-11-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0013_specialty_cathedras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='cathedras',
        ),
    ]
