# Generated by Django 4.2.7 on 2023-11-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0014_remove_specialty_cathedras'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='code',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
