# Generated by Django 4.2.7 on 2023-11-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0015_specialty_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cathedra',
            name='specialties',
        ),
        migrations.DeleteModel(
            name='CathedraSpecialty',
        ),
    ]
