# Generated by Django 4.2.7 on 2023-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0016_remove_cathedra_specialties_delete_cathedraspecialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Веріфіковано'),
        ),
    ]
