# Generated by Django 4.2.7 on 2023-11-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vstup', '0017_entrant_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrant',
            name='who_verified',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Хто перевірив відомості'),
        ),
    ]
