# Generated by Django 4.2.7 on 2023-11-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0018_entrant_user_entrant_who_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrant',
            name='user',
        ),
    ]
