# Generated by Django 4.2.7 on 2023-12-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0019_remove_entrant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='entrant',
            name='personal_data_processing',
            field=models.BooleanField(default=False, verbose_name='Згода на обробку персональних даних'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='foreign_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.foreignlanguage', verbose_name='Іноземна мова (вступний іспит)'),
        ),
    ]
