# Generated by Django 4.2.7 on 2023-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0020_foreignlanguage_entrant_personal_data_processing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='personal_data_processing',
            field=models.BooleanField(verbose_name='Згода на обробку персональних даних'),
        ),
    ]
