# Generated by Django 4.2.7 on 2023-12-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0021_alter_entrant_personal_data_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='personal_data_processing',
            field=models.BooleanField(default=True, verbose_name='Згода на обробку персональних даних'),
        ),
    ]
