# Generated by Django 4.2.7 on 2023-12-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0022_alter_entrant_personal_data_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='entrant',
            name='diploma_specialty',
            field=models.CharField(default='000', max_length=50, verbose_name='Код та назва спеціальності, зазначені в дипломі'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.specialty', verbose_name='Спеціальність, за якою вступаєте до аспірантури'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='education_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.educationform', verbose_name='Форма навчання'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='funding_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.fundingsource', verbose_name='Джерело фінансування (очна форма)'),
        ),
    ]
