# Generated by Django 4.2.7 on 2023-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0023_educationform_fundingsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
