# Generated by Django 4.2.7 on 2023-12-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0024_alter_fundingsource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='approval_notification',
            field=models.BooleanField(default=False, verbose_name='Чи потребуєту повідомлення про допуск до вступних іспитів для оформлення за місцем роботи додаткової відпустки'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='dormitory_accommodation',
            field=models.BooleanField(default=False, verbose_name='Чи потребуєту поселення в гуртожиток на час складання вступних іспитів'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='scientific_advisor',
            field=models.CharField(default=' Rs', max_length=20, verbose_name='Прізвище передбачуваного наукового керівника'),
        ),
    ]
