# Generated by Django 4.2.7 on 2023-12-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0026_alter_entrant_scientific_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='filling_form_date',
            field=models.DateTimeField(default='1980-01-01', verbose_name='Дата заповнення форми'),
        ),
    ]
