# Generated by Django 4.2.7 on 2023-12-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0027_entrant_filling_form_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='filling_form_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заповнення форми'),
        ),
    ]
