# Generated by Django 4.2.7 on 2023-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0028_alter_entrant_filling_form_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='additional_tests',
            field=models.BooleanField(default=False, verbose_name='Додаткові вступні випробування'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='competition_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Конкурсний бал'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='grade_foreign_language',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Оцінка за іноземну мову'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='grade_scientific_achievements',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Оцінка за іноземну мову'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='grade_specialty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Оцінка за спеціальність'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='need_additional_tests',
            field=models.BooleanField(default=False, verbose_name='Необхідність у додаткових вступних випробуваннях'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендовано до зарахування за державним замовленням'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='diploma_avg',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Середній бал диплому про вищу освіту (зазначений у додатку до диплому)', max_digits=5, verbose_name='Середній бал диплому'),
        ),
    ]
