# Generated by Django 4.2.7 on 2023-12-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0031_remove_specialty_cathedras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='entrant',
            name='vidrahovano',
            field=models.BooleanField(default=False, verbose_name='Відраховано'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.order', verbose_name='Наказ про зарахування'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='studing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.studinggroup', verbose_name='Навчальна група'),
        ),
    ]
