# Generated by Django 4.2.7 on 2023-12-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0032_order_studinggroup_alter_specialty_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cathedra',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='entrant',
            old_name='cathedra',
            new_name='department',
        ),
    ]
