# Generated by Django 4.2.7 on 2023-12-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0034_remove_entrant_filling_form_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.AlterField(
            model_name='entrant',
            name='electronic_queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vstup.electronicqueue', verbose_name='Електронна черга'),
        ),
    ]
