# Generated by Django 4.2.7 on 2023-12-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0035_electronicqueue_alter_entrant_electronic_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='entrant',
            name='level',
            field=models.IntegerField(choices=[(2, 'Магістр (професійний рівень)'), (3, 'Спеціаліст')], default=3, verbose_name='Рівень диплому про вищу освіту'),
        ),
    ]
