# Generated by Django 4.2.7 on 2023-12-14 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0036_timing_alter_entrant_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timing',
        ),
        migrations.AlterModelOptions(
            name='electronicqueue',
            options={},
        ),
        migrations.RemoveField(
            model_name='electronicqueue',
            name='slot',
        ),
        migrations.AddField(
            model_name='electronicqueue',
            name='datetime',
            field=models.DateTimeField(default=datetime.date(2023, 7, 1)),
        ),
    ]
