# Generated by Django 4.2.7 on 2023-12-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0037_delete_timing_alter_electronicqueue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicqueue',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
