# Generated by Django 4.2.7 on 2023-12-14 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0038_alter_electronicqueue_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicqueue',
            name='datetime',
            field=models.DateTimeField(default=datetime.date(2023, 7, 1)),
        ),
    ]
