# Generated by Django 4.2.7 on 2023-12-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0039_alter_electronicqueue_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicqueue',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
