# Generated by Django 4.2.7 on 2023-12-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0043_alter_electronicqueue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicqueue',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
