# Generated by Django 4.2.7 on 2023-12-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0044_alter_electronicqueue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='electronic_queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vstup.electronicqueue', verbose_name='Електронна черга'),
        ),
    ]
