# Generated by Django 4.2.7 on 2023-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0046_entrant_notes_alter_entrant_approval_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='short_name',
            field=models.CharField(default='держзамов.', max_length=10),
        ),
    ]
