# Generated by Django 4.2.7 on 2023-12-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstup', '0051_alter_entrant_approval_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='approval_notification',
            field=models.BooleanField(default=False, verbose_name='Повідомлення для оформлення додаткової відпустки'),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='dormitory_accommodation',
            field=models.BooleanField(default=False, verbose_name='Потреба у гуртожитку на час складання іспитів'),
        ),
    ]
